/**
 * Medi AI — knowledge base expansion pack.
 * Loaded by server.js at boot: any topic not already in the database is
 * added once (existing topics are never duplicated or overwritten).
 *
 * Entry format: [topic, searchKeywords, summary, advice, severity, source]
 * DISCLAIMER: general educational reference only — NOT a substitute for
 * professional medical advice. No dosages are included on purpose.
 */
'use strict';

module.exports = [

  /* ---------------- lab reports (powers Report Lens) ---------------- */
  ['Complete blood count (CBC) explained',
   'cbc blood count hemoglobin wbc rbc platelets report meaning full blood',
   'A CBC measures hemoglobin (oxygen-carrying capacity), WBC (infection-fighting cells), RBC, hematocrit and platelets (clotting cells). Adult hemoglobin is roughly 12–16 g/dL for women and 13–17 g/dL for men. High WBC often means infection; low WBC can follow some viral illnesses or medicines.',
   'Never treat a single number — doctors interpret patterns with your symptoms. Marked anemia, very high/low WBC or platelets below normal needs medical review. Bring the full report to a physician rather than treating yourself.',
   'see-doctor'],
  ['HbA1c and blood sugar ranges',
   'hba1c fasting sugar post prandial pp glucose diabetes test range report',
   'HbA1c shows average blood sugar over ~3 months: below 5.7% is normal, 5.7–6.4% is pre-diabetes, 6.5% or above on two tests suggests diabetes. Fasting sugar 70–100 mg/dL is normal; 100–125 is pre-diabetic; above 126 suggests diabetes. Post-meal (PP) values above 200 mg/dL are also suggestive.',
   'Diagnosis and treatment need a doctor — never start or stop diabetes medicines yourself. Pre-diabetes can often be reversed with diet, weight loss and 30 minutes of daily walking.',
   'see-doctor'],
  ['Lipid profile (cholesterol test)',
   'lipid profile cholesterol ldl hdl triglycerides vldl report non hdl',
   'The lipid profile measures LDL ("bad" cholesterol — lower is better), HDL ("good" — higher is better) and triglycerides. As a general guide LDL under 100 mg/dL and triglycerides under 150 mg/dL are desirable, but target numbers vary by age, diabetes and heart risk.',
   'A single mildly off value rarely needs panic — repeat after 8–12 weeks of diet change. Very high triglycerides (above 500) need prompt medical care because of pancreatitis risk.',
   'see-doctor'],
  ['Thyroid profile (TSH, T3, T4)',
   'tsh t3 t4 thyroid profile report hypothyroid hyperthyroid thyroid test',
   'TSH is the brain signal controlling the thyroid. High TSH with low T4 usually means an underactive thyroid (weight gain, tiredness, cold intolerance); low TSH with high T4 suggests an overactive thyroid (weight loss, palpitations, heat intolerance). Normal TSH is roughly 0.4–4.0 mIU/L but labs vary.',
   'Thyroid medicines are precise — dose changes must come from a doctor with the full report. Untreated thyroid problems in pregnancy are serious, so pregnant women should never miss follow-ups.',
   'see-doctor'],
  ['Liver function tests (LFT)',
   'lft liver function test alt ast bilirubin alkaline phosphatase sgot sgpt report',
   'LFTs measure enzymes (ALT/SGPT, AST/SGOT), bilirubin and proteins that reflect liver health. Mild enzyme rises are common with fatty liver, alcohol, some medicines and recent viral illness. Bilirubin rise causes jaundice (yellow eyes/skin).',
   'Stop alcohol and avoid unnecessary painkillers while awaiting review. Marked enzyme elevation, jaundice, drowsiness or abdominal swelling needs urgent medical care.',
   'see-doctor'],
  ['Kidney function tests (creatinine, eGFR)',
   'creatinine urea egfr kidney function test report bun kidney report meaning',
   'Creatinine and urea are waste products cleared by the kidneys; eGFR estimates filtering capacity (90+ is normal for most adults). Rising creatinine or falling eGFR means the kidneys need assessment — dehydration, some painkillers and uncontrolled BP/sugar are common contributors.',
   'Avoid NSAID painkillers (like ibuprofen/diclofenac) until a doctor reviews the report, and stay well hydrated. A sudden sharp fall in urine output with these results is urgent.',
   'see-doctor'],
  ['Vitamin D and B12 test ranges',
   'vitamin d 25 oh deficiency test b12 range report deficiency level',
   'Vitamin D below ~20 ng/mL is commonly treated as deficiency (bone pain, tiredness); B12 below ~200 pg/mL may cause tingling, fatigue and memory issues. Both deficiencies are extremely common in Indian diets, especially in vegetarians (B12 comes mainly from animal foods and fortified items).',
   'Deficiency correction (dose and duration) should be guided by a doctor based on your level — high-dose self-supplementation is not always safe. Sunlight exposure of 15–20 minutes helps vitamin D.',
   'see-doctor'],
  ['Urine routine examination',
   'urine test routine examination pus cells protein sugar ketones urine report meaning',
   'A urine routine checks pus cells (infection markers), protein (kidney stress), sugar and ketones. A few pus cells can be normal; protein or sugar in urine repeatedly needs medical review — protein can signal early kidney disease and sugar can point to diabetes.',
   'Repeat the test with a clean midstream sample if the first result is odd. Fever with burning urine and pus cells suggests a UTI needing treatment.',
   'see-doctor'],
  ['How to read a lab report safely',
   'lab report reading understanding reference range abnormal values flagged how to understand',
   'Lab reports compare you against a reference range covering most healthy people — being slightly outside a range is common and often harmless. Labs also differ slightly in methods, so compare results from the same lab where possible. Values marked with H (high) or L (low) are guides, not diagnoses.',
   'Never start or stop treatment because of one number. Take the full report to a doctor who knows your history, and keep old reports — trends matter more than single readings.',
   'self-care'],

  /* ---------------- conditions not yet covered ---------------- */
  ['Sinusitis (sinus infection)',
   'sinus sinusitis facial pressure blocked nose headache behind eyes post nasal drip',
   'Sinusitis is inflammation of the air-filled facial sinuses, usually after a cold: thick nasal discharge, facial pressure or pain (worse bending forward), blocked nose and reduced smell. Most cases are viral and improve in 7–10 days.',
   'Steam inhalation, saline nasal rinses, warm fluids and rest help. See a doctor if symptoms last over 10 days, there is high fever, swelling around the eye, vision change or severe one-sided facial pain.',
   'see-doctor'],
  ['Sore throat / tonsillitis',
   'sore throat tonsillitis tonsil throat pain swallowing white patches strep',
   'Most sore throats are viral and settle in 3–7 days. Tonsillitis with fever, swollen neck glands and white patches on the tonsils can be bacterial and may need antibiotics after examination.',
   'Warm salt-water gargles, warm fluids and honey soothe. See a doctor for trouble breathing or swallowing, drooling, high fever with white patches, or symptoms beyond a week. Antibiotics must be prescribed, never self-started.',
   'see-doctor'],
  ['Peptic ulcer & H. pylori',
   'ulcer stomach burning peptic gastritis h pylori pain hunger black stool',
   'Peptic ulcers are sores in the stomach/duodenal lining, often from H. pylori bacteria or regular painkiller use. Classic burning upper abdominal pain often improves with food and returns hours later.',
   'Get medical evaluation — H. pylori needs a tested course of medicines. Black/tarry stools, coffee-ground vomit or sudden severe abdominal pain means urgent hospital care.',
   'see-doctor'],
  ['Motion sickness',
   'motion sickness travel nausea vomiting car bus dizziness queasy',
   'Motion sickness happens when the inner ear and eyes send conflicting movement signals — nausea, cold sweat and dizziness during car, bus or boat travel.',
   'Sit in the front seat or over the wings, look at the horizon, avoid reading, keep air flowing and eat light before travel. Anti-sickness medicines from a pharmacist work best taken 30–60 minutes before the journey.',
   'self-care'],
  ['Thalassemia basics',
   'thalassemia trait anemia inherited blood test low hemoglobin small red cells carrier',
   'Thalassemia is an inherited blood condition where the body makes less hemoglobin, causing anemia of varying degree. Many Indians carry thalassemia trait (minor) — mild anemia discovered on tests, usually needing no treatment but important for family planning.',
   'If a blood test shows long-standing mild anemia with small red cells that does not respond to iron, ask about thalassemia testing. Carriers should get genetic counselling before marriage/planning children. Severe forms need specialist blood care.',
   'see-doctor'],
  ['Sickle cell disease',
   'sickle cell anemia pain crisis inherited blood bone pain jaundice',
   'Sickle cell disease makes red blood cells rigid and C-shaped, blocking small vessels and causing severe pain "crises" (often bones/back/chest), anemia and infections. It is inherited — common in parts of central and southern India.',
   'Pain crises, fever, chest pain or sudden severe tiredness need medical attention fast. Daily folic acid, hydration, avoiding extreme heat/dehydration and vaccination are pillars of care, managed by a specialist.',
   'emergency'],
  ['Cataract',
   'cataract blurry vision cloudy lens white pupil glasses not helping elderly',
   'A cataract is clouding of the eye lens, mostly with age: gradual blurring, glare from lights, faded colors and frequent spectacle changes. It is the leading cause of treatable blindness in India.',
   'Surgery is safe, quick and highly effective when vision starts limiting daily life. Sudden eye pain, redness or vision loss is NOT typical cataract — seek urgent eye care.',
   'see-doctor'],
  ['Glaucoma (eye pressure)',
   'glaucoma eye pressure silent vision loss peripheral family screening',
   'Glaucoma damages the optic nerve, usually due to high eye pressure. The common type is silent — peripheral vision shrinks so slowly people notice late. Family history raises risk, and diabetes increases it.',
   'After age 40, get an eye pressure check every 1–2 years (earlier with family history). Acute glaucoma with eye pain, headache, halos around lights and blurred vision is an emergency.',
   'see-doctor'],
  ['Diabetic retinopathy (eye check)',
   'diabetes eye check retina laser photo blurred vision floaters diabetic eye',
   'High sugar damages the retina\'s tiny blood vessels — diabetic retinopathy is a top cause of blindness in working-age Indians. Early stages have NO symptoms; only a retina exam (dilated or fundus photo) catches it.',
   'Everyone with diabetes needs a retina check at least once a year even with perfect vision. Seeing floaters, shadows or sudden blur needs prompt eye review.',
   'see-doctor'],
  ['Chronic kidney disease (CKD)',
   'ckd chronic kidney creatinine protein urine swelling legs blood pressure diabetes',
   'CKD is gradual, permanent kidney weakening — usually silent for years. Diabetes and high BP are the two biggest causes in India. Signs appear late: leg swelling, fatigue, poor appetite, night-time urination.',
   'Protect kidneys by controlling sugar and BP strictly, avoiding regular NSAID painkillers, avoiding unverified herbal or protein supplements, and keeping all follow-up blood tests. Nephrology review slows progression.',
   'see-doctor'],
  ['Lactose intolerance',
   'lactose intolerance milk dairy gas bloating diarrhea after milk curd',
   'Lactose intolerance — very common in Indians — means the gut lacks the enzyme for milk sugar, causing bloating, cramps and diarrhoea within hours of milk. Curd/paneer are usually better tolerated than milk.',
   'Use curd, buttermilk, paneer or lactose-free milk; watch calcium intake otherwise. Losing weight, blood in stool or symptoms even without dairy is not typical — get checked.',
   'self-care'],
  ['Celiac disease / gluten',
   'celiac gluten wheat allergy loose motion bloating anemia child not growing',
   'Celiac disease is an immune reaction to gluten (wheat, barley, rye) damaging the small intestine: chronic diarrhoea, bloating, anemia and poor growth in children. It needs blood tests (tTG-IgA) and confirmation.',
   'Treatment is a strict lifelong gluten-free diet guided by a doctor/dietitian. Do NOT start a gluten-free diet before testing — it makes the tests falsely normal.',
   'see-doctor'],
  ['Eye strain & screen time',
   'eye strain screen dry eyes blurry computer phone 20 20 20 rule',
   'Digital eye strain causes tired, dry, aching eyes, blurred vision and headaches after long screen sessions. It is uncomfortable but does not permanently damage the eyes.',
   'Follow the 20-20-20 rule: every 20 minutes look 20 feet away for 20 seconds. Blink often, keep screens slightly below eye level, reduce glare and use lubricating eye drops if dry. Sudden vision loss or eye pain is different — seek care.',
   'self-care'],
  ['Food allergy vs food intolerance',
   'food allergy intolerance peanut hives swelling itching stomach difference test',
   'Food allergy is an immune reaction that can be severe (hives, lip/tongue swelling, vomiting, breathing trouble within minutes); intolerance (like lactose) is uncomfortable but not life-threatening — gas, cramps, diarrhoea.',
   'Any swelling of lips/tongue, throat tightness or dizziness after food is an emergency — call 112. Suspected allergies should be assessed and tested; do not self-diagnose broad food bans.',
   'see-doctor'],

  /* ---------------- common Indian medicines (brand guide, no doses) ---------------- */
  ['Paracetamol brands in India (Crocin, Dolo, Calpol, P-500)',
   'crocin dolo calpol paracetamol p 650 fever medicine brand generic safe dose',
   'Crocin, Dolo-650, Calpol and P-500 all contain the same medicine — paracetamol — just from different companies. It is the safest first choice for fever and mild pain in most people, including pregnancy.',
   'Take as per the label/doctor and never exceed the daily maximum stated on the pack; taking two paracetamol brands together doubles the dose dangerously. Avoid alcohol with it. Never give aspirin to children with fever.',
   'self-care'],
  ['Painkiller brands & safety (Combiflam, Voveran, Volini)',
   'combiflam ibuprofen voveran diclofenac volini moov painkiller safe nsaid gel',
   'Combiflam = ibuprofen + paracetamol; Voveran = diclofenac. These NSAIDs reduce pain and swelling but can harm the stomach, kidneys and blood pressure with frequent use, and can be risky in dengue and kidney disease.',
   'Use the lowest dose for the shortest time, with food. Gels like Volini/Moov are safer for muscle pain than tablets. People with kidney disease, gastritis, heart issues or on blood thinners should ask a doctor first. Recurring pain needs a diagnosis, not repeated painkillers.',
   'self-care'],
  ['Cold, cough & allergy brands (cetirizine, montelukast, cough syrups)',
   'cetirizine cetzine okacet montek montelukast cold cough syrup benadryl alex',
   'Cetirizine (Cetzine etc.) treats sneezing, runny nose and allergy — once a day, may cause mild sleepiness. Montelukast (Montek etc.) is prescribed for allergy/asthma prevention. Many cough syrups contain multiple ingredients; codeine-based ones are strictly prescription.',
   'Do not combine a "cold and flu" tablet with a separate paracetamol — most already contain it. Cough lasting over 2–3 weeks, blood-streaked sputum, breathlessness or high fever needs a doctor, not another syrup.',
   'self-care'],

  /* ---------------- drug interactions (top ones) ---------------- */
  ['Interaction: blood thinners + painkillers',
   'warfarin aspirin clopidogrel ibuprofen blood thinner interaction bleeding',
   'Blood thinners (warfarin, clopidogrel, apixaban) plus NSAID painkillers (ibuprofen, diclofenac) sharply raise bleeding risk — stomach bleeds can occur with little warning.',
   'Paracetamol is the usual safer painkiller on blood thinners. Always tell every doctor and pharmacist what blood thinner you take before any new medicine, including Ayurvedic or "herbal" products.',
   'see-doctor'],
  ['Interaction: antibiotics + antacids/iron/calcium',
   'ciprofloxacin azithromycin antacid iron calcium interaction gap timing',
   'Ciprofloxacin-type antibiotics bind to iron, calcium and antacids, losing effect. Azithromycin absorbs worse with antacids.',
   'Keep a 2-hour gap before and 4–6 hours after the antibiotic for iron/calcium/antacid doses, or ask the pharmacist to plan the timings. Finish the full antibiotic course exactly as prescribed.',
   'self-care'],
  ['Interaction: metformin + alcohol / scans',
   'metformin alcohol contrast scan ct lactic acidosis interaction diabetes',
   'Metformin with heavy alcohol risks lactic acidosis (rare but dangerous). IV contrast dye used in CT scans also interacts with metformin.',
   'Tell the scan department you take metformin — it is usually paused around the scan and restarted after kidney checks. Avoid alcohol while on metformin. Seek urgent care for vomiting, deep rapid breathing or severe weakness.',
   'see-doctor'],
  ['Interaction: statins + certain antibiotics',
   'statin atorvastatin clarithromycin erythromycin muscle pain interaction',
   'Clarithromycin/erythromycin-type antibiotics raise statin levels, risking serious muscle damage — unexplained muscle pain, weakness or dark urine.',
   'Always tell the doctor prescribing an antibiotic that you take a statin. New muscle pain after starting any new medicine deserves a check.',
   'see-doctor'],

  /* ---------------- home remedies (safe, common) ---------------- */
  ['Home remedies: cold, cough & sore throat',
   'home remedy cold cough sore throat haldi milk turmeric ginger honey tulsi steam',
   'Traditional, generally safe supports: warm turmeric milk (haldi doodh), ginger-tulsi tea with honey (honey only above 1 year of age), salt-water gargles and plain steam inhalation.',
   'These ease symptoms — they do not cure infections. Avoid honey in babies under 1 year (infant botulism risk). No remedy replaces a doctor when breathing is hard, fever is high or illness lasts beyond 7–10 days.',
   'self-care'],
  ['Home remedies: digestion & acidity',
   'home remedy digestion acidity jeera ajwain saunf fennel gas bloating',
   'Commonly used and generally safe: jeera (cumin) water, ajwain (carom) with warm water, saunf (fennel) after meals, mint tea and eating slower.',
   'These suit occasional indigestion. Alarm signs — weight loss, difficulty swallowing, vomiting blood, black stools or pain radiating to the chest/arm — need a doctor, not remedies.',
   'self-care'],
  ['Home remedies: hydration & summer',
   'ors hydration summer nimbu pani coconut water salt sugar water dehydration drink',
   'For dehydration and heat: ORS packets are the gold standard; homemade alternatives include nimbu pani (lemon + sugar + a pinch of salt) and tender coconut water. Drink before feeling thirsty in summer.',
   'Watch urine colour — dark means drink more. Confusion, no urine for 8+ hours, or fainting in heat needs medical care (possible heat stroke).',
   'self-care'],

];
